apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: sonarr
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: "15.3.0"
  values:
    image:
      repository: ghcr.io/onedr0p/sonarr
      tag: "4.0.14.2938"  # override default
    env:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: sonarr.sleepy-puppy.com
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - sonarr.sleepy-puppy.com
            secretName: sonarr-tls
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config
